# webdavfs
name: release

# on events
on:
  release:
    types: 
        - created

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/mips, linux/mipsle'
            package: ''
            name: 'webdavfs'
            compress: 'true'
            dest: 'dist'
      - name: Install upx
        working-directory: /tmp
        env:
          CC: clang
          CXX: clang++
        run: |
          set -ex
          git clone --recursive https://github.com/upx/upx.git
          cd upx
          make
          cp build/release/upx /usr/local/bin/upx
      - name: Upx compress binary
        run: |
          cd ./dist
          tar -xvzf webdavfs-linux-mips.tar.gz -C .
          upx webdavfs
          tar -cvzf webdavfs-linux-mips.tar.gz webdavfs README.md
          tar -xvzf webdavfs-linux-mipsel.tar.gz -C .
          upx webdavfs
          tar -cvzf webdavfs-linux-mipsle.tar.gz webdavfs README.md
      - name: Upload build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*.tar.gz"
